- name: Create kubernetes cluster master node
  remote_user: root
  hosts: kube_master
  gather_facts: no
  vars_files:
    - ../common_vars.yml
  vars:
    base_path: '/opt/deploy/kubernetes'
    kubeadm_init_host: "{{ hostvars.kube_join.kubeadm_init_host }}"   
    kubeadm_master_certificateKey: "{{ hostvars.kube_join.kubeadm_master_certificateKey }}"
    kubeadm_token: "{{ hostvars.kube_join.kubeadm_token }}"
    kubeadm_discovery_token_ca_cert_hash: "{{ hostvars.kube_join.kubeadm_discovery_token_ca_cert_hash }}"
    controlPlaneVip: "{{ kubernetes.controlPlaneVip }}"
    controlPlanePort: "{{ kubernetes.controlPlanePort }}"
  tasks:
    - name: Create directory
      file:
        path: '{{ base_path }}/deb/'
        state: directory
      when: ansible_ssh_host != kubeadm_init_host

    - name: Copy kubernetes package
      copy:
        src: '../../resources/package/{{ item }}'
        dest: '{{ base_path }}/deb/'
      loop: [ "kubernetes-1.22.0" ]
      when: ansible_ssh_host != kubeadm_init_host

    - name: Install base soft lib
      shell:
        cmd: 'dpkg -i {{ base_path }}/deb/{{ item }}/base/*.deb'
        chdir: '{{ base_path }}/deb/'
      loop: [ "kubernetes-1.22.0" ]
      when: ansible_ssh_host != kubeadm_init_host

    - name: Install kubeadm kubelet kubectl
      shell:
        cmd: 'dpkg -i {{ base_path }}/deb/{{ item }}/*.deb'
        chdir: '{{ base_path }}/deb/'
      loop: [ "kubernetes-1.22.0" ]
      when: ansible_ssh_host != kubeadm_init_host

    - name: Restart kubelet
      systemd:
        name: kubelet
        state: restarted
        enabled: yes
      when: ansible_ssh_host != kubeadm_init_host

    - name: View kubernetes master node join command
      debug:
        msg: "kubeadm join {{ controlPlaneVip }}:6443 --token {{ kubeadm_token }} --discovery-token-ca-cert-hash sha256:{{ kubeadm_discovery_token_ca_cert_hash }} --control-plane --certificate-key {{ kubeadm_master_certificateKey }} --v=5"
      register: kube_join_debug
      when: ansible_ssh_host != kubeadm_init_host

    - name: Master node Join to cluster
      shell: "{{ kube_join_debug.msg }} > {{ base_path }}/kube_master_join.log;{{ base_path }}/check_k8sconf.sh"
      register: response
      until: response.stdout.find('kubernetes conf exist') != -1
      retries: 3
      delay: 5
      when: ansible_ssh_host != kubeadm_init_host

    - name: Create kubernetes kubectl config file
      shell: "mkdir -p $HOME/.kube; cp -i /etc/kubernetes/admin.conf $HOME/.kube/config; chown $(id -u):$(id -g) $HOME/.kube/config"
      when: ansible_ssh_host != kubeadm_init_host